### ISSUE TITLE
Add components

### ISSUE THREAD

**Issue by hitgo00** [hitgo00/yasn-mobile#2]
The following components are to be implemented/modified using `native-base` or some other component lib:
- Profile details
- Post Card (including Comment collapse, add Comment)
- User details form

**Comment by bhavesh0206s** [comment]
I can work on this issue

**Comment by hitgo00** [comment]
Great, go ahead @bhavesh0206s.

**Comment by bhavesh0206s** [comment]
Hey can you help me with what fields are required in Profile Details and User Details

**Comment by hitgo00** [comment]
<img width="386" alt="Screenshot 2020-10-09 at 5 18 34 PM" src="https://user-images.githubusercontent.com/41156157/95579558-81223c80-0a53-11eb-8294-a376e38e6295.png">
Profile card similar to this 👆🏻.

On the first sign in the user will be asked to complete the sign up form with following details:
`name: {
    type: String,
    required: true,
  },
  email: {
    type: String,
    required: true,
  },
  username: {
    type: String,
    required: true,
    trim: true,
    maxlength: 20,
  },

  bio: String,
  picUrl: String, (can be skipped for now)
  gitHubUrl: String,
  linkedInUrl: String,
  instaUrl: String,
  clubsComm: [String] (will be multiple options to select like sports committee, music club, programming club etc and user can select 0 or more)`

![IMG_4523](https://user-images.githubusercontent.com/41156157/95580863-ae6fea00-0a55-11eb-8f1c-4d9f24fc6efe.jpg)
